name: course
channels:
  - conda-forge
dependencies:
  - cmasher=1.6.3
  - jupyter=1.0.0
  - lxml=4.9.1
  - pandas=1.4.3
  - pillow=9.2.0
  - pyarrow=9.0.0
  - requests=2.28.1
  - scipy=1.9.0
  - seaborn=0.11.2
  - sphinx=5.1.1
  - sphinx-gallery=0.11.0
  - sphinx_rtd_theme=1.0.0
  - matplotlib=3.5.3
  - numpy=1.23.1
  - scikit-learn=1.1.2
  - linkify-it-py=2.0.0
  - pip=22.2.2
  - xgboost=1.6.2
  - tensorflow=2.9.1
  - umap-learn=0.5.3
  - pip:
      - adjustText
      - highlight-text
      - kloppy
      - mplsoccer
      - sphinxcontrib-youtube=
      - myst-parser
      - ruptures

